In [1]:
# To do numerical analysis we use the numpy package

In [4]:
import numpy as np

In [5]:
# Define a Python list
my_list = [1,2,3]

In [7]:
# Convert the list to a numpy array
my_array = np.asarray(my_list)

my_list

In [8]:
my_array

array([1, 2, 3])

In [9]:
my_list

[1, 2, 3]

In [10]:
# The single bracket indicates a one-dimensional array
my_array

array([1, 2, 3])

In [11]:
# Create a list
A_list = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
# Convert this to a numpy array

In [18]:
A_array = np.asarray (A_list)

In [17]:
# Note the double brackets
# This indicates a two-dimensional array
A_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Create a numpy array (ID) with 'arange'
min_value = 0
max_value = 10 # Exclusive
my_array = np.arange(min_value,max_value)

In [22]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [25]:
np.arange(-3.14,3.14)

array([-3.14, -2.14, -1.14, -0.14,  0.86,  1.86,  2.86])

In [26]:
np.arange(-5.4,7.8,2.1)

array([-5.4, -3.3, -1.2,  0.9,  3. ,  5.1,  7.2])

In [27]:
min_value = -9.8
max_value = 17.45
step_size = 3.67
my_array1 = np.arange(min_value,max_value,step_size)
print('my_array: ', my_array1)

my_array:  [-9.8  -6.13 -2.46  1.21  4.88  8.55 12.22 15.89]


In [28]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
# To create !D arrays we use 'linspace'
# Create an array with equally spaced values
min_value = 0
max_value = 10
number_of_grid_points = 5
my_grid = np.linspace(min_value,max_value,number_of_grid_points)
print ('my_grid: ', my_grid)

my_grid:  [ 0.   2.5  5.   7.5 10. ]


In [38]:
np.random.rand(5)

array([0.91875528, 0.37940503, 0.01709211, 0.23345716, 0.13161956])

In [39]:
np.random.rand(10)

array([0.17539359, 0.83697442, 0.46584321, 0.95810149, 0.09937537,
       0.46418373, 0.4755499 , 0.45861886, 0.31399569, 0.67156274])

In [40]:
# To create random numbers from the unform distribution
Nx = 4
np.random.rand(Nx)

array([0.86851224, 0.95090455, 0.46444784, 0.3761684 ])

In [41]:
# Create random nymbers from the normal/gausian distribution
Nx = 4
np.random.randn(Nx)

array([ 1.57700291, -1.08822518,  0.1691009 ,  1.1881765 ])

In [42]:
np.random.randn(3,3)

array([[-0.26567758, -0.60696797,  1.11536641],
       [ 0.2015537 , -0.82481301,  0.40520693],
       [-0.49792467,  1.14328344,  0.52177513]])

In [43]:
# Create a random integer between 1 and 50
np.random.randint(1,50)

1

In [45]:
# Create 3 random integers between 1 and 50
np.random.randint(1,50,3)

array([40, 19, 15])

In [46]:
my_array = np.random.randint(0,100,50)

In [47]:
my_array

array([45, 25, 39, 25, 60,  5, 78, 21,  4, 80, 11, 61,  7, 38, 82, 62, 96,
       38, 67, 72,  2, 79, 20, 71, 27, 21, 82, 72, 91, 18,  9, 56, 92, 11,
       47, 75, 66, 97, 11,  4, 26, 18, 37, 42, 50, 49, 81, 94, 56, 44])

In [48]:
# The reshape method allows us to change the dimensions of an array
my_array.reshape(5,10)

array([[45, 25, 39, 25, 60,  5, 78, 21,  4, 80],
       [11, 61,  7, 38, 82, 62, 96, 38, 67, 72],
       [ 2, 79, 20, 71, 27, 21, 82, 72, 91, 18],
       [ 9, 56, 92, 11, 47, 75, 66, 97, 11,  4],
       [26, 18, 37, 42, 50, 49, 81, 94, 56, 44]])

In [56]:
#my_array.reshape(5,5)

In [50]:
my_array.reshape(2,25)

array([[45, 25, 39, 25, 60,  5, 78, 21,  4, 80, 11, 61,  7, 38, 82, 62,
        96, 38, 67, 72,  2, 79, 20, 71, 27],
       [21, 82, 72, 91, 18,  9, 56, 92, 11, 47, 75, 66, 97, 11,  4, 26,
        18, 37, 42, 50, 49, 81, 94, 56, 44]])

In [51]:
# To get the maximum value
my_array.max()

97

In [52]:
# To get the minimum value
my_array.min()

2

In [53]:
# To get the position of the maximum value
my_array.argmax()

37

In [54]:
# To get the position of the minimum value
my_array.argmin()

20

In [55]:
my_array.shape

(50,)

In [57]:
# The original array is not changed when u reshape

In [58]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
my_array = np.arange(0,10)

In [60]:
my_array.shape

(10,)

In [62]:
# Array slicing.
my_array[:2]

array([0, 1])

In [63]:
# Array slicing
my_array[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# Array slicing
my_array[2:6]

array([2, 3, 4, 5])

In [65]:
# Broadcasting
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# Broadcast a value to elements 
my_array[0:4] = 100

In [67]:
my_array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [75]:
slice_of_array = my_array[0:5]

In [77]:
slice_of_array

array([100, 100, 100, 100,   4])

In [78]:
my_array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [82]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [83]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
my_matrix.shape

(3, 3)

In [85]:
# First element of matrix.
# Remember, Python counts from zero
my_matrix[0,0] # This is called single bracket notation

1

In [86]:
my_matrix[0][0] # This is called double bracket notation

1

In [88]:
my_matrix.size # The number of elements in the array

9

In [89]:
my_array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [90]:
my_array > 5 # Output is a boolean

array([ True,  True,  True,  True, False, False,  True,  True,  True,
        True])

In [91]:
my_array[my_array > 5] 

array([100, 100, 100, 100,   6,   7,   8,   9])

In [92]:
my_array[my_array < 5]

array([4])

In [97]:
my_array = np.array([1,2,3,4,5])

In [98]:
# Numpy operations
# We can apply any operation to the array
# Operations are applied "element-wise"

In [99]:
my_array

array([1, 2, 3, 4, 5])

In [100]:
my_array  + my_array

array([ 2,  4,  6,  8, 10])

In [101]:
my_array/my_array

array([1., 1., 1., 1., 1.])

In [102]:
7*my_array

array([ 7, 14, 21, 28, 35])

In [103]:
my_array/7

array([0.14285714, 0.28571429, 0.42857143, 0.57142857, 0.71428571])

In [104]:
np.sqrt(my_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [105]:
np.exp(my_array)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])